# Compass Dashboard

In [1]:
import pandas as pd

In [45]:
shift_data = {
    'month':['march','march','march'],
    'day':['Sunday','Monday','Tuesday'],
    'start':[1445,1445,1445],
    'end':[1835,1835,1835]
}

shifts = pd.DataFrame(shift_data)
shifts

   month      day  start   end
0  march   Sunday   1445  1835
1  march   Monday   1445  1835
2  march  Tuesday   1445  1835

In [46]:
fare_data = {
    '1zone': 2.70,
    '2zone': 4.00,
    '1zonemonth': 111.60,
    '2zonemonth': 149.25,
    '2zoneaddfare': 1.50,
    'yvraddfare' : 5.00
}
fare_data

{'1zone': 2.7,
 '2zone': 4.0,
 '1zonemonth': 111.6,
 '2zonemonth': 149.25,
 '2zoneaddfare': 1.5,
 'yvraddfare': 5.0}

In [48]:
def ShiftsToTrips(df:pd.DataFrame):
    "Convert a shifts schedule to the implied commute schedule"
    trips = df.copy()
    trips['start'] = df['start'] - 100
    trips.rename(columns={'start':'home','end':'YVR'}, inplace=True)
    trips = trips.melt(id_vars=['month','day'],
                        value_vars=['home','YVR'],
                        var_name='origin',
                        value_name='time')
    return trips

In [49]:
ShiftsToTrips(shifts)

   month      day origin  time
0  march   Sunday   home  1345
1  march   Monday   home  1345
2  march  Tuesday   home  1345
3  march   Sunday    YVR  1835
4  march   Monday    YVR  1835
5  march  Tuesday    YVR  1835

In [ ]:
def GetOneZoneTrips(df:pd.DataFrame):
    "Find all trips that occur on a weekend or after 6:30pm"
    one_zone = df.loc[(df['day'].isin(['Saturday','Sunday'])) | (df['time']>1800)]

    return one_zone

GetOneZoneTrips(trips)

   month      day origin  time
0  march   Sunday   home  1345
3  march   Sunday    YVR  1835
4  march   Monday    YVR  1835
5  march  Tuesday    YVR  1835

In [66]:
def GetTwoZoneTrips(df:pd.DataFrame):
    "find all trips that occur on a weekday before 6:30pm"
    two_zone = df.loc[(df['day'].isin(['Monday','Tuesday','Wednesday','Thursday','Friday']) & (df['time']<1800))]

    return two_zone

GetTwoZoneTrips(trips)

   month      day origin  time
1  march   Monday   home  1345
2  march  Tuesday   home  1345

In [57]:
def GetAddFareTrips(df:pd.DataFrame):
    "find all trips that will incur the YVR add fare"
    add_fare = df.loc[df['origin'] == 'YVR']

    return add_fare

GetAddFareTrips(trips)

   month      day origin  time
3  march   Sunday    YVR  1835
4  march   Monday    YVR  1835
5  march  Tuesday    YVR  1835

In [77]:
def TotalCost(shifts:pd.DataFrame, fares:dict, method:str):
    "find the total cost of commuting based on the given method"

    # convert shifts to trips
    trips = ShiftsToTrips(shifts)

    # count one zone trips
    OneZone = GetOneZoneTrips(trips).shape[0]

    # count two zone trips
    TwoZone = GetTwoZoneTrips(trips).shape[0]

    # count add fare trips
    AddFare = GetAddFareTrips(trips).shape[0]

    if method == 'StoredValue':
        TotalCost = OneZone*fares['1zone'] + TwoZone*fares['2zone'] + AddFare*fares['yvraddfare']
        return TotalCost
    if method == 'OneZoneMonthly':
        TotalCost = fares['1zonemonth'] + TwoZone*fares['2zoneaddfare']
        return TotalCost
    if method == 'TwoZoneMonthly':
        TotalCost = fares['2zonemonth']
        return TotalCost

    return None

TotalCost(shifts, fare_data, 'StoredValue')

33.8

In [78]:
CommuteCost = {
    'Stored Value' : TotalCost(shifts, fare_data, 'StoredValue'),
    '1 Zone Month Pass' : TotalCost(shifts, fare_data, 'OneZoneMonthly'),
    '2 Zone Month Pass' : TotalCost(shifts, fare_data, 'TwoZoneMonthly')
}

pd.DataFrame(CommuteCost, index=range(1))

   Stored Value  1 Zone Month Pass  2 Zone Month Pass
0          33.8              114.6             149.25

## Preprocessing

In [1]:
text = open("MAR 2026.txt").read()

In [2]:
text

'MAR 2026\nMon \n02-Mar \nTue \n03-Mar \nWed \n04-Mar \nThu \n05-Mar \nFri \n06-Mar \nSat \n07-Mar \nSun \n08-Mar\nRatna \nSalim\n\n\n1445-1845  \nAGT1\n\n\n\n\n1445-1845  \nAGT1\n\n\n\n\nAlex \nYe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAnn \nKim\n\n\n1445-1845  \nAGT1\n1445-1845  \nAGT1\n\n\n1415-1815  \nTKT\n\n\n1545-1945  \nAGT1\nSaeko \nSumi\n\n\n1215-1915 FC \n1215-1915 FC \n1215-1915 FC \n1215-1915 FC \n1215-1915 FC\n\n\nJoey \nLu\n1115-1915  \nSUP\n1115-1915  \nSUP\n\n\n1115-1915  \nSUP\n\n\n1115-1915  \nSUP\n1215-2015  \nOPS\nCindy \nXiao\n\n\n\n\n1145-1845  \nARR+DEP\n\n\n1445-1845  \nAGT1\n\n\n1245-1945  \nARR+DEP\nSatomi \nHarward\n1145-1845  \nARR+DEP\n1145-1845  \nARR+DEP\n\n\n\n\n1145-1845  \nARR+DEP\n1145-1845  \nARR+DEP\n1245-1945  \nARR+DEP\nKohei \nTodoroki\n\n\n1415-1815  \nTKT\n\n\n1415-1815  \nTKT\n\n\n\n\n1515-1915  \nTKT\nRich \nHung\n\n\n\n\n\n\n1445-1845  \nAGT1\n\n\n1445-1845  \nAGT1\n\n\nCecillia  \nZhu\n\n\n\n\n1145-1845 WT 1145-1845 WT \n\n\n\n\n1145-1845 WT 1145-1845 WT\n1245-1945 WT\nDonia  \nForbes\n1445-1845  \nAGT1\n\n\n1445-1845  \nAGT1\n1445-1845  \nAGT1\n\n\n\n\n\n\nKevin \nLee\n1145-1845  \nARR+DEP\n1145-1845  \nARR+DEP\n\n\n\n\n\n\n\n\n\n\nCrystal  \nDeng\n1215-1915 FC\n\n\n\n\n1145-1845  \nARR+DEP\n1145-1845  \nARR+DEP\n1145-1845  \nARR+DEP\n1315-2015 FC\nEunsol \nChoi\n1445-1845  \nAGT1\n1445-1845  \nAGT1\n\n\n1445-1845  \nAGT1\n1445-1845  \nAGT1\n\n\n\n\nAngel  \nYeh\n1415-1815  \nTKT\n\n\n1145-1815  \nARR+TKT\n1145-1845  \nARR+DEP\n\n\n1415-1815  \nTKT\n1545-1945  \nAGT1\nWillow \nPark\n\n\n1445-1845  \nAGT1\n\n\n1445-1845  \nAGT1\n\n\n\n\n\n\nYumi  \nKwon\n1445-1845  \nAGT1\n1115-1915  \nOPS\n1445-1845  \nAGT1\n1115-1915  \nOPS\n\n\n1115-1915  \nOPS\n\n\nJoJo \nWang\n\n\n\n\n\n\n\n\n1445-1845  \nAGT1\n1445-1845  \nAGT1\n1545-1945  \nAGT1\nRJ \nArellano\n1145-1845 WT\n1445-1845  \nAGT1\n1445-1845  \nAGT1\n1145-1845 WT\n1445-1845  \nAGT1\n\n\n\n\nCody \nLeung\n1115-1915  \nOPS\n\n\n1115-1915  \nOPS\n\n\n1115-1915  \nOPS\n\n\n\n\nIan \nMaccarthy\n1445-1845  \nAGT1\n\n\n1445-1845  \nAGT1\n1445-1845  \nAGT1\n\n\n1445-1845  \nAGT1\n1545-1945  \nAGT1\nHarleen \nHothi\n1445-1845  \nAGT1\n\n\n1445-1845  \nAGT1\n\n\n\n\n1445-1845  \nAGT1\n\n\nChloe \nWang\n\n\n\n\n\n\n\n\n\n\n1445-1845  \nAGT1\n1545-1945  \nAGT1\n\n\n\nMAR 2026\nMon \n09-Mar \nTue \n10-Mar \nWed \n11-Mar \nThu \n12-Mar \nFri \n13-Mar \nSat \n14-Mar \nSun \n15-Mar\nRatna \nSalim\n\n\n1545-1945  \nAGT1\n\n\n\n\n1545-1945  \nAGT1\n\n\n\n\nAlex \nYe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAnn \nKim\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1515-1915  \nTKT\n\n\n\n\nSaeko \nSumi\n\n\n\n\n1315-2015 FC 1315-2015 FC\n1315-2015 FC \n1315-2015 FC \n1315-2015 FC\n\n\nJoey \nLu\n1215-2015  \nSUP\n1215-2015  \nSUP\n1215-2015  \nSUP\n\n\n\n\n1215-2015  \nOPS\n1315-2015 FC\nCindy \nXiao\n\n\n\n\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n\n\n\n\nSatomi \nHarward\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\nKohei \nTodoroki\n\n\n1515-1915  \nTKT\n\n\n1515-1915  \nTKT\n\n\n\n\n1515-1915  \nTKT\nRich \nHung\n\n\n\n\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\nCecillia  \nZhu\n\n\n\n\n1245-1945 WT 1245-1945 WT \n\n\n\n\n1245-1945 WT 1245-1945 WT\n1245-1945 WT\nDonia  \nForbes\n1545-1945  \nAGT1\n\n\n\n\n\n\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\nKevin \nLee\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\n\n\n\n\n\n\n1545-1945  \nAGT1\n\n\nCrystal  \nDeng\n1315-2015 FC\n1245-1945  \nARR+DEP\n\n\n\n\n\n\n\n\n\n\nEunsol \nChoi\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n\n\nAngel  \nYeh\n1515-1915  \nTKT\n\n\n1515-1915  \nTKT\n1245-1945  \nARR+DEP\n\n\n1245-1915  \nARR+TKT\n1245-1945  \nARR+DEP\nWillow \nPark\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n\n\n\n\nYumi  \nKwon\n1215-2015  \nOPS\n1215-2015  \nOPS\n1545-1945  \nAGT1\n1215-2015  \nOPS\n\n\n1545-1945  \nAGT1\n\n\nJoJo \nWang\n\n\n\n\n\n\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\nRJ \nArellano\n1245-1945 WT\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1245-1945 WT\n1545-1945  \nAGT1\n\n\n\n\nCody \nLeung\n\n\n\n\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\nIan \nMaccarthy\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n1245-1945  \nARR+DEP\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\nHarleen \nHothi\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\nChloe \nWang\n1545-1945  \nAGT1\n\n\n\n\n\n\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n\nMAR 2026\nMon \n16-Mar \nTue \n17-Mar \nWed \n18-Mar \nThu \n19-Mar \nFri \n20-Mar \nSat \n21-Mar \nSun \n22-Mar\nRatna \nSalim\n\n\n1545-1945  \nAGT1\n\n\n\n\n1545-1945  \nAGT1\n\n\n\n\nAlex \nYe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAnn \nKim\n\n\n1545-1945  \nAGT1\n1515-1915  \nTKT\n1545-1945  \nAGT1\n1515-1915  \nTKT\n\n\n\n\nSaeko \nSumi\n\n\n1315-2015 FC \n1315-2015 FC \n1315-2015 FC \n1315-2015 FC \n1315-2015 FC\n\n\nJoey \nLu\n1215-2015  \nSUP\n1215-2015  \nSUP\n\n\n1215-2015  \nSUP\n\n\n1215-2015  \nOPS\n1215-2015  \nSUP\nCindy \nXiao\n\n\n\n\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n\n\n\n\nSatomi \nHarward\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\nKohei \nTodoroki\n\n\n1515-1915  \nTKT\n\n\n1515-1915  \nTKT\n\n\n\n\n1515-1915  \nTKT\nRich \nHung\n\n\n\n\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\nCecillia  \nZhu\n\n\n\n\n1245-1945 WT 1245-1945 WT \n\n\n\n\n\n\n1245-1945 WT 1245-1945 WT\nDonia  \nForbes\n1545-1945  \nAGT1\n\n\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\nKevin \nLee\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\n\n\n\n\n\n\n\n\n\n\nCrystal  \nDeng\n1315-2015 FC\n\n\n\n\n\n\n1545-1945  \nAGT1\n1245-1945  \nARR+DEP\n1315-2015 FC\nEunsol \nChoi\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n\n\nAngel  \nYeh\n1515-1915  \nTKT\n1245-1945  \nARR+DEP\n\n\n1245-1915  \nARR+TKT\n\n\n1515-1915  \nTKT\n1245-1915  \nARR+TKT\nWillow \nPark\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n\n\n\n\nYumi  \nKwon\n1215-2015  \nOPS\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\nJoJo \nWang\n\n\n\n\n\n\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\nRJ \nArellano\n1245-1945 WT\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n1245-1945 WT 1245-1945 WT\n\n\n\n\nCody \nLeung\n\n\n\n\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\nIan \nMaccarthy\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n1245-1945  \nARR+DEP\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\nHarleen \nHothi\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n\n\n\n\n1545-1945  \nAGT1\nChloe \nWang\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n\nMAR 2026\nMon \n23-Mar \nTue \n24-Mar \nWed \n25-Mar \nThu \n26-Mar \nFri \n27-Mar \nSat \n28-Mar \nSun \n29-Mar\nRatna \nSalim\n\n\n1545-1945  \nAGT1\n\n\n\n\n1545-1945  \nAGT1\n\n\n\n\nAlex \nYe\n\n\n\n\n1245-1945  \nARR+DEP\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n1615-2015  \nAGT1\nAnn \nKim\n\n\n1545-1945  \nAGT1\n1515-1915  \nTKT\n1545-1945  \nAGT1\n1515-1915  \nTKT\n\n\n\n\nSaeko \nSumi\n\n\n1315-2015 FC \n1315-2015 FC \n1315-2015 FC \n1315-2015 FC \n1315-2015 FC\n\n\nJoey \nLu\n1215-2015  \nSUP\n1215-2015  \nSUP\n\n\n1215-2015  \nSUP\n1215-2015  \nSUP\n\n\n1230-2015  \nSUP\nCindy \nXiao\n\n\n1245-1945  \nARR+DEP\n\n\n\n\n1245-1945  \nARR+DEP\n\n\n\n\nSatomi \nHarward\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n\n\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\n1230-2000  \nARR+DEP\nKohei \nTodoroki\n\n\n1515-1915  \nTKT\n\n\n1515-1915  \nTKT\n\n\n1515-1915  \nTKT\n\n\nRich \nHung\n\n\n\n\n\n\n\n\n\n\n1545-1945  \nAGT1\n\n\nCecillia  \nZhu\n\n\n\n\n1245-1945 WT 1245-1945 WT \n\n\n\n\n\n\n1245-1945 WT 1230-2000 WT\nDonia  \nForbes\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n\n\n\n\n\n\nKevin \nLee\n1245-1945  \nARR+DEP\n1245-1945  \nARR+DEP\n\n\n\n\n\n\n\n\n\n\nCrystal  \nDeng\n1315-2015 FC\n\n\n\n\n1245-1945  \nARR+DEP\n1545-1945  \nAGT1\n1245-1945  \nARR+DEP\n1315-2015 FC\nEunsol \nChoi\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n\n\n\n\nAngel  \nYeh\n1515-1915  \nTKT\n\n\n\n\n1245-1915  \nARR+TKT\n\n\n1545-1945  \nAGT1\n1230-1930  \nARR+TKT\nWillow \nPark\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n\n\n\n\nYumi  \nKwon\n1545-1945  \nAGT1\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\n1615-2015  \nAGT1\nJoJo \nWang\n\n\n\n\n\n\n\n\n1545-1945  \nAGT1\n\n\n1615-2015  \nAGT1\nRJ \nArellano\n1245-1945 WT\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n1245-1945 WT 1245-1945 WT\n\n\n\n\nCody \nLeung\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\n\n\n1215-2015  \nOPS\nIan \nMaccarthy\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n1615-2015  \nAGT1\nHarleen \nHothi\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n1545-1945  \nAGT1\n\n\n1615-2015  \nAGT1\nChloe \nWang\n\n\n\n\n1545-1945  \nAGT1\n\n\n\n\n1545-1945  \nAGT1\n1615-2015  \nAGT1\n\n\n\nMAR 2026\nMon \n30-Mar \nTue \n31-Mar \nWed \n01-Apr \nThu \n02-Apr \nFri \n03-Apr \nSat \n04-Apr \nSun \n05-Apr\nRatna \nSalim\n\n\n\n\n1615-2015  \nAGT1\n\n\n\n\n\n\n\n\nAlex \nYe\n1615-2015  \nAGT1\n\n\n\n\n1615-2015  \nAGT1\n1715-2115  \nAGT1\n1230-2100  \nARR+DEP\n1715-2115  \nGT1\nAnn \nKim\n\n\n1530-1930  \nTKT\n1530-1930  \nTKT\n1530-1930  \nTKT\n1630-2030  \nTKT\n\n\n\n\nSaeko \nSumi\n\n\n1315-2015 FC \n1315-2015 FC \n1315-2015 FC \n1415-2115 FC \n1415-2115 FC\n\n\nJoey \nLu\n1230-2015  \nSUP\n1230-2015  \nSUP\n\n\n1230-2015  \nSUP\n\n\n1215-2115  \nOPS\n1330-2115  \nSUP\nCindy \nXiao\n\n\n1230-2000  \nARR+DEP\n\n\n\n\n1230-2100  \nARR+DEP\n\n\n\n\nSatomi \nHarward\n1230-2000  \nARR+DEP\n\n\n1230-2000  \nARR+DEP\n1230-2000  \nARR+DEP\n1230-2100  \nARR+DEP\n1230-2100  \nARR+DEP\n\n\nKohei \nTodoroki\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nRich \nHung\n\n\n\n\n\n\n1615-2015  \nAGT1\n\n\n\n\n\n\nCecillia  \nZhu\n\n\n\n\n1230-2000 WT 1230-2000 WT \n\n\n\n\n\n\n1230-2100 WT 1330-2100 WT\nDonia  \nForbes\n1615-2015  \nAGT1\n\n\n1615-2015  \nAGT1\n\n\n\n\n\n\n\n\nKevin \nLee\n1230-2000  \nARR+DEP\n1230-2000  \nARR+DEP\n\n\n\n\n\n\n\n\n\n\nCrystal  \nDeng\n1315-2015 FC\n\n\n\n\n\n\n1715-2115  \nAGT1\n1715-2115  \nAGT1\n1415-2115 FC\nEunsol \nChoi\n1615-2015  \nAGT1\n1615-2015  \nAGT1\n1615-2015  \nAGT1\n1615-2015  \nAGT1\n1715-2115  \nAGT1\n\n\n\n\nAngel  \nYeh\n1530-1930  \nTKT\n\n\n\n\n1230-2000  \nARR+DEP\n\n\n1630-2030  \nTKT\n1330-2030  \nARR+TKT\nWillow \nPark\n\n\n1615-2015  \nAGT1\n\n\n1615-2015  \nAGT1\n\n\n\n\n\n\nYumi  \nKwon\n\n\n1215-2015  \nOPS\n1215-2015  \nOPS\n1215-2015  \nOPS\n\n\n1715-2115  \nAGT1\n1715-2115  \nGT1\nJoJo \nWang\n\n\n\n\n\n\n\n\n1715-2115  \nAGT1\n\n\n1715-2115  \nGT1\nRJ \nArellano\n1230-2000 WT\n1615-2015  \nAGT1\n1615-2015  \nAGT1\n\n\n1230-2000 WT 1230-2100 WT\n\n\n\n\nCody \nLeung\n1215-2015  \nOPS\n\n\n\n\n\n\n1215-2115  \nOPS\n\n\n1315-2115  \nOPS\nIan \nMaccarthy\n1615-2015  \nAGT1\n1615-2015  \nAGT1\n\n\n1615-2015  \nAGT1\n\n\n1715-2115  \nAGT1\n1330-2100  \nARR+DEP\nHarleen \nHothi\n1615-2015  \nAGT1\n\n\n1615-2015  \nAGT1\n\n\n\n\n1715-2115  \nAGT1\n1715-2115  \nGT1\nChloe \nWang\n\n\n1615-2015  \nAGT1\n1230-2000  \nARR+DEP\n\n\n1715-2115  \nAGT1\n1715-2115  \nAGT1\n1715-2115  \nGT1\n\n\n\n'

In [9]:
import csv
file_path = "MAR 2026.txt"

with open(file_path, mode='r') as file:
    reader = csv.reader(file, delimiter='\n')
    elements = [row for row in reader]

In [16]:
elements[15:31]

[['Ratna '],
 ['Salim'],
 [],
 [],
 ['1445-1845  '],
 ['AGT1'],
 [],
 [],
 [],
 [],
 ['1445-1845  '],
 ['AGT1'],
 [],
 [],
 [],
 []]

In [18]:
elements[15][0]+elements[16][0]

'Ratna Salim'

In [25]:
entries = []
left = 1
right = 2

while right < len(elements):
    entry = elements[left]+elements[right]
    if len(entry) >1:
         entry = entry[0]+entry[1]   
    entries.append(entry)
    left+=2
    right+=2

In [29]:
entries[7:15]

['Ratna Salim', [], '1445-1845  AGT1', [], [], '1445-1845  AGT1', [], []]

In [37]:
left=7
right=15
while right<len(entries):
    print(entries[left:right])
    left+=8
    right+=8

['Ratna Salim', [], '1445-1845  AGT1', [], [], '1445-1845  AGT1', [], []]
['Alex Ye', [], [], [], [], [], [], []]
['Ann Kim', [], '1445-1845  AGT1', '1445-1845  AGT1', [], '1415-1815  TKT', [], '1545-1945  AGT1']
['Saeko Sumi', [], '1215-1915 FC 1215-1915 FC ', '1215-1915 FC 1215-1915 FC ', ['1215-1915 FC'], ['Joey '], 'Lu1115-1915  ', 'SUP1115-1915  ']
[['SUP'], ['1115-1915  '], ['SUP'], ['1115-1915  '], 'SUP1215-2015  ', 'OPSCindy ', ['Xiao'], []]
[['1145-1845  '], ['ARR+DEP'], ['1445-1845  '], ['AGT1'], ['1245-1945  '], 'ARR+DEPSatomi ', 'Harward1145-1845  ', 'ARR+DEP1145-1845  ']
[['ARR+DEP'], [], ['1145-1845  '], 'ARR+DEP1145-1845  ', 'ARR+DEP1245-1945  ', 'ARR+DEPKohei ', ['Todoroki'], ['1415-1815  ']]
[['TKT'], ['1415-1815  '], ['TKT'], [], ['1515-1915  '], 'TKTRich ', ['Hung'], []]
[[], ['1445-1845  '], ['AGT1'], ['1445-1845  '], ['AGT1'], ['Cecillia  '], ['Zhu'], []]
[['1145-1845 WT 1145-1845 WT '], [], [], '1145-1845 WT 1145-1845 WT1245-1945 WT', 'Donia  Forbes', '1445-1845  AGT1', [], '1445-1845  AGT1']
['1445-1845  AGT1', [], [], [], 'Kevin Lee', '1145-1845  ARR+DEP', '1145-1845  ARR+DEP', []]
[[], [], [], [], 'Crystal  Deng', ['1215-1915 FC'], [], ['1145-1845  ']]
['ARR+DEP1145-1845  ', 'ARR+DEP1145-1845  ', 'ARR+DEP1315-2015 FC', 'Eunsol Choi', '1445-1845  AGT1', '1445-1845  AGT1', [], '1445-1845  AGT1']
['1445-1845  AGT1', [], [], 'Angel  Yeh', '1415-1815  TKT', [], '1145-1815  ARR+TKT', '1145-1845  ARR+DEP']
[[], '1415-1815  TKT', '1545-1945  AGT1', 'Willow Park', [], '1445-1845  AGT1', [], '1445-1845  AGT1']
[[], [], [], 'Yumi  Kwon', '1445-1845  AGT1', '1115-1915  OPS', '1445-1845  AGT1', '1115-1915  OPS']
[[], '1115-1915  OPS', [], 'JoJo Wang', [], [], [], []]
['1445-1845  AGT1', '1445-1845  AGT1', '1545-1945  AGT1', 'RJ Arellano', '1145-1845 WT1445-1845  ', 'AGT11445-1845  ', 'AGT11145-1845 WT', '1445-1845  AGT1']
[[], [], 'Cody Leung', '1115-1915  OPS', [], '1115-1915  OPS', [], '1115-1915  OPS']
[[], [], 'Ian Maccarthy', '1445-1845  AGT1', [], '1445-1845  AGT1', '1445-1845  AGT1', []]
['1445-1845  AGT1', '1545-1945  AGT1', 'Harleen Hothi', '1445-1845  AGT1', [], '1445-1845  AGT1', [], []]
['1445-1845  AGT1', [], 'Chloe Wang', [], [], [], [], []]
['1445-1845  AGT1', '1545-1945  AGT1', [], ['MAR 2026'], 'Mon 09-Mar ', 'Tue 10-Mar ', 'Wed 11-Mar ', 'Thu 12-Mar ']
['Fri 13-Mar ', 'Sat 14-Mar ', 'Sun 15-Mar', 'Ratna Salim', [], '1545-1945  AGT1', [], []]
['1545-1945  AGT1', [], [], 'Alex Ye', [], [], [], []]
[[], [], [], 'Ann Kim', [], '1545-1945  AGT1', '1545-1945  AGT1', '1545-1945  AGT1']
['1515-1915  TKT', [], [], 'Saeko Sumi', [], [], '1315-2015 FC 1315-2015 FC1315-2015 FC ', '1315-2015 FC 1315-2015 FC']
[[], 'Joey Lu', '1215-2015  SUP', '1215-2015  SUP', '1215-2015  SUP', [], [], '1215-2015  OPS']
['1315-2015 FCCindy ', ['Xiao'], [], ['1245-1945  '], ['ARR+DEP'], ['1245-1945  '], ['ARR+DEP'], []]
[['Satomi '], 'Harward1245-1945  ', ['ARR+DEP'], ['1245-1945  '], ['ARR+DEP'], ['1245-1945  '], 'ARR+DEP1245-1945  ', 'ARR+DEP1245-1945  ']
['ARR+DEPKohei ', ['Todoroki'], ['1515-1915  '], ['TKT'], ['1515-1915  '], ['TKT'], [], ['1515-1915  ']]
['TKTRich ', ['Hung'], [], [], ['1545-1945  '], ['AGT1'], ['1545-1945  '], ['AGT1']]
[['Cecillia  '], ['Zhu'], [], ['1245-1945 WT 1245-1945 WT '], [], [], '1245-1945 WT 1245-1945 WT1245-1945 WT', 'Donia  Forbes']
['1545-1945  AGT1', [], [], [], [], '1545-1945  AGT1', '1545-1945  AGT1', 'Kevin Lee']
['1245-1945  ARR+DEP', '1245-1945  ARR+DEP', [], [], [], '1545-1945  AGT1', [], 'Crystal  Deng']
['1315-2015 FC1245-1945  ', ['ARR+DEP'], [], [], [], [], ['Eunsol '], 'Choi1545-1945  ']
['AGT11545-1945  ', ['AGT1'], ['1545-1945  '], 'AGT11545-1945  ', ['AGT1'], [], ['Angel  '], 'Yeh1515-1915  ']
[['TKT'], ['1515-1915  '], 'TKT1245-1945  ', ['ARR+DEP'], ['1245-1915  '], 'ARR+TKT1245-1945  ', 'ARR+DEPWillow ', ['Park']]
[['1545-1945  '], ['AGT1'], ['1545-1945  '], ['AGT1'], [], [], ['Yumi  '], 'Kwon1215-2015  ']
['OPS1215-2015  ', 'OPS1545-1945  ', 'AGT11215-2015  ', ['OPS'], ['1545-1945  '], ['AGT1'], ['JoJo '], ['Wang']]
[[], [], [], ['1545-1945  '], ['AGT1'], ['1545-1945  '], 'AGT1RJ ', 'Arellano1245-1945 WT']
['1545-1945  AGT1', '1545-1945  AGT1', '1245-1945 WT1545-1945  ', ['AGT1'], [], ['Cody '], ['Leung'], []]
[['1215-2015  '], ['OPS'], ['1215-2015  '], ['OPS'], ['1215-2015  '], 'OPSIan ', 'Maccarthy1545-1945  ', ['AGT1']]
[['1545-1945  '], 'AGT11245-1945  ', ['ARR+DEP'], ['1545-1945  '], 'AGT11545-1945  ', 'AGT1Harleen ', 'Hothi1545-1945  ', ['AGT1']]
[['1545-1945  '], ['AGT1'], ['1545-1945  '], ['AGT1'], ['1545-1945  '], 'AGT1Chloe ', 'Wang1545-1945  ', ['AGT1']]
[[], [], [], ['1545-1945  '], 'AGT11545-1945  ', ['AGT1'], [], 'MAR 2026Mon ']
['16-Mar Tue ', '17-Mar Wed ', '18-Mar Thu ', '19-Mar Fri ', '20-Mar Sat ', '21-Mar Sun ', '22-MarRatna ', ['Salim']]
[['1545-1945  '], ['AGT1'], [], ['1545-1945  '], ['AGT1'], [], ['Alex '], ['Ye']]
[[], [], [], [], [], [], ['Ann '], ['Kim']]
[['1545-1945  '], 'AGT11515-1915  ', 'TKT1545-1945  ', 'AGT11515-1915  ', ['TKT'], [], ['Saeko '], ['Sumi']]
[['1315-2015 FC '], '1315-2015 FC 1315-2015 FC ', '1315-2015 FC 1315-2015 FC', [], 'Joey Lu', '1215-2015  SUP', '1215-2015  SUP', []]
['1215-2015  SUP', [], '1215-2015  OPS', '1215-2015  SUP', 'Cindy Xiao', [], [], '1245-1945  ARR+DEP']
[[], '1245-1945  ARR+DEP', [], [], 'Satomi Harward', '1245-1945  ARR+DEP', [], '1245-1945  ARR+DEP']
[[], '1245-1945  ARR+DEP', '1245-1945  ARR+DEP', '1245-1945  ARR+DEP', 'Kohei Todoroki', [], '1515-1915  TKT', []]
['1515-1915  TKT', [], [], '1515-1915  TKT', 'Rich Hung', [], [], []]
['1545-1945  AGT1', [], '1545-1945  AGT1', [], 'Cecillia  Zhu', [], [], ['1245-1945 WT 1245-1945 WT ']]
[[], [], ['1245-1945 WT 1245-1945 WT'], 'Donia  Forbes', '1545-1945  AGT1', [], [], '1545-1945  AGT1']
[[], '1545-1945  AGT1', [], 'Kevin Lee', '1245-1945  ARR+DEP', '1245-1945  ARR+DEP', [], []]
[[], [], [], 'Crystal  Deng', ['1315-2015 FC'], [], [], ['1545-1945  ']]
['AGT11245-1945  ', 'ARR+DEP1315-2015 FC', 'Eunsol Choi', '1545-1945  AGT1', '1545-1945  AGT1', '1545-1945  AGT1', '1545-1945  AGT1', '1545-1945  AGT1']
[[], [], 'Angel  Yeh', '1515-1915  TKT', '1245-1945  ARR+DEP', [], '1245-1915  ARR+TKT', []]
['1515-1915  TKT', '1245-1915  ARR+TKT', 'Willow Park', [], '1545-1945  AGT1', [], '1545-1945  AGT1', []]
[[], [], 'Yumi  Kwon', '1215-2015  OPS', '1215-2015  OPS', [], '1215-2015  OPS', '1545-1945  AGT1']
['1545-1945  AGT1', [], 'JoJo Wang', [], [], [], [], '1545-1945  AGT1']
[[], '1545-1945  AGT1', 'RJ Arellano', '1245-1945 WT1545-1945  ', 'AGT11545-1945  ', ['AGT1'], ['1245-1945 WT 1245-1945 WT'], []]
[[], 'Cody Leung', [], [], '1215-2015  OPS', [], '1215-2015  OPS', []]
['1215-2015  OPS', 'Ian Maccarthy', '1545-1945  AGT1', [], '1545-1945  AGT1', '1245-1945  ARR+DEP', [], '1545-1945  AGT1']
['1545-1945  AGT1', 'Harleen Hothi', '1545-1945  AGT1', [], '1545-1945  AGT1', [], [], []]
['1545-1945  AGT1', 'Chloe Wang', '1545-1945  AGT1', [], '1545-1945  AGT1', [], [], '1545-1945  AGT1']
['1545-1945  AGT1', [], ['MAR 2026'], 'Mon 23-Mar ', 'Tue 24-Mar ', 'Wed 25-Mar ', 'Thu 26-Mar ', 'Fri 27-Mar ']
['Sat 28-Mar ', 'Sun 29-Mar', 'Ratna Salim', [], '1545-1945  AGT1', [], [], '1545-1945  AGT1']
[[], [], 'Alex Ye', [], [], '1245-1945  ARR+DEP', '1545-1945  AGT1', '1545-1945  AGT1']
['1545-1945  AGT1', '1615-2015  AGT1', 'Ann Kim', [], '1545-1945  AGT1', '1515-1915  TKT', '1545-1945  AGT1', '1515-1915  TKT']
[[], [], 'Saeko Sumi', [], '1315-2015 FC 1315-2015 FC ', '1315-2015 FC 1315-2015 FC ', ['1315-2015 FC'], ['Joey ']]
['Lu1215-2015  ', 'SUP1215-2015  ', ['SUP'], ['1215-2015  '], 'SUP1215-2015  ', ['SUP'], ['1230-2015  '], 'SUPCindy ']
[['Xiao'], ['1245-1945  '], ['ARR+DEP'], [], ['1245-1945  '], ['ARR+DEP'], [], ['Satomi ']]
['Harward1245-1945  ', ['ARR+DEP'], ['1245-1945  '], ['ARR+DEP'], ['1245-1945  '], 'ARR+DEP1245-1945  ', 'ARR+DEP1230-2000  ', 'ARR+DEPKohei ']
[['Todoroki'], ['1515-1915  '], ['TKT'], ['1515-1915  '], ['TKT'], ['1515-1915  '], ['TKT'], ['Rich ']]
[['Hung'], [], [], [], [], ['1545-1945  '], ['AGT1'], ['Cecillia  ']]
[['Zhu'], [], ['1245-1945 WT 1245-1945 WT '], [], [], [], '1245-1945 WT 1230-2000 WTDonia  ', 'Forbes1545-1945  ']
[['AGT1'], ['1545-1945  '], ['AGT1'], [], [], [], ['Kevin '], 'Lee1245-1945  ']
['ARR+DEP1245-1945  ', ['ARR+DEP'], [], [], [], [], ['Crystal  '], 'Deng1315-2015 FC']
[[], [], '1245-1945  ARR+DEP', '1545-1945  AGT1', '1245-1945  ARR+DEP', '1315-2015 FCEunsol ', 'Choi1545-1945  ', 'AGT11545-1945  ']
[['AGT1'], ['1545-1945  '], ['AGT1'], [], [], ['Angel  '], 'Yeh1515-1915  ', ['TKT']]
[[], ['1245-1915  '], ['ARR+TKT'], ['1545-1945  '], 'AGT11230-1930  ', 'ARR+TKTWillow ', ['Park'], ['1545-1945  ']]
[['AGT1'], ['1545-1945  '], ['AGT1'], [], [], ['Yumi  '], 'Kwon1545-1945  ', 'AGT11215-2015  ']
[['OPS'], ['1215-2015  '], ['OPS'], ['1215-2015  '], 'OPS1615-2015  ', 'AGT1JoJo ', ['Wang'], []]
[[], [], ['1545-1945  '], ['AGT1'], ['1615-2015  '], 'AGT1RJ ', 'Arellano1245-1945 WT', '1545-1945  AGT1']
['1545-1945  AGT1', [], ['1245-1945 WT 1245-1945 WT'], [], ['Cody '], 'Leung1215-2015  ', ['OPS'], ['1215-2015  ']]
[['OPS'], ['1215-2015  '], ['OPS'], ['1215-2015  '], 'OPSIan ', 'Maccarthy1545-1945  ', ['AGT1'], ['1545-1945  ']]
['AGT11545-1945  ', ['AGT1'], ['1545-1945  '], 'AGT11615-2015  ', 'AGT1Harleen ', 'Hothi1545-1945  ', ['AGT1'], ['1545-1945  ']]
[['AGT1'], ['1545-1945  '], ['AGT1'], ['1615-2015  '], 'AGT1Chloe ', ['Wang'], [], ['1545-1945  ']]
[['AGT1'], [], ['1545-1945  '], 'AGT11615-2015  ', ['AGT1'], [], 'MAR 2026Mon ', '30-Mar Tue ']
['31-Mar Wed ', '01-Apr Thu ', '02-Apr Fri ', '03-Apr Sat ', '04-Apr Sun ', '05-AprRatna ', ['Salim'], []]
[['1615-2015  '], ['AGT1'], [], [], [], ['Alex '], 'Ye1615-2015  ', ['AGT1']]
[[], ['1615-2015  '], 'AGT11715-2115  ', 'AGT11230-2100  ', 'ARR+DEP1715-2115  ', 'GT1Ann ', ['Kim'], ['1530-1930  ']]
['TKT1530-1930  ', 'TKT1530-1930  ', 'TKT1630-2030  ', ['TKT'], [], ['Saeko '], ['Sumi'], ['1315-2015 FC ']]
['1315-2015 FC 1315-2015 FC ', '1415-2115 FC 1415-2115 FC', [], 'Joey Lu', '1230-2015  SUP', '1230-2015  SUP', [], '1230-2015  SUP']
[[], '1215-2115  OPS', '1330-2115  SUP', 'Cindy Xiao', [], '1230-2000  ARR+DEP', [], []]
['1230-2100  ARR+DEP', [], [], 'Satomi Harward', '1230-2000  ARR+DEP', [], '1230-2000  ARR+DEP', '1230-2000  ARR+DEP']
['1230-2100  ARR+DEP', '1230-2100  ARR+DEP', [], 'Kohei Todoroki', [], [], [], []]
[[], [], [], 'Rich Hung', [], [], [], '1615-2015  AGT1']
[[], [], [], 'Cecillia  Zhu', [], [], ['1230-2000 WT 1230-2000 WT '], []]
[[], ['1230-2100 WT 1330-2100 WT'], 'Donia  Forbes', '1615-2015  AGT1', [], '1615-2015  AGT1', [], []]
[[], [], 'Kevin Lee', '1230-2000  ARR+DEP', '1230-2000  ARR+DEP', [], [], []]
[[], [], 'Crystal  Deng', ['1315-2015 FC'], [], [], ['1715-2115  '], 'AGT11715-2115  ']
['AGT11415-2115 FC', 'Eunsol Choi', '1615-2015  AGT1', '1615-2015  AGT1', '1615-2015  AGT1', '1615-2015  AGT1', '1715-2115  AGT1', []]
[[], 'Angel  Yeh', '1530-1930  TKT', [], [], '1230-2000  ARR+DEP', [], '1630-2030  TKT']
['1330-2030  ARR+TKT', 'Willow Park', [], '1615-2015  AGT1', [], '1615-2015  AGT1', [], []]
[[], 'Yumi  Kwon', [], '1215-2015  OPS', '1215-2015  OPS', '1215-2015  OPS', [], '1715-2115  AGT1']
['1715-2115  GT1', 'JoJo Wang', [], [], [], [], '1715-2115  AGT1', []]
['1715-2115  GT1', 'RJ Arellano', '1230-2000 WT1615-2015  ', 'AGT11615-2015  ', ['AGT1'], ['1230-2000 WT 1230-2100 WT'], [], []]
['Cody Leung', '1215-2015  OPS', [], [], [], '1215-2115  OPS', [], '1315-2115  OPS']
['Ian Maccarthy', '1615-2015  AGT1', '1615-2015  AGT1', [], '1615-2015  AGT1', [], '1715-2115  AGT1', '1330-2100  ARR+DEP']
['Harleen Hothi', '1615-2015  AGT1', [], '1615-2015  AGT1', [], [], '1715-2115  AGT1', '1715-2115  GT1']
['Chloe Wang', [], '1615-2015  AGT1', '1230-2000  ARR+DEP', [], '1715-2115  AGT1', '1715-2115  AGT1', '1715-2115  GT1']

In [6]:
import pdfplumber

with pdfplumber.open("Monthly Schedule _ MAR.pdf") as pdf:
    page = pdf.pages[0]
    table = page.extract_table()

print(table)

[['MAR 2026', 'Mon\n02-Mar', 'Tue\n03-Mar', 'Wed\n04-Mar', 'Thu\n05-Mar', 'Fri\n06-Mar', 'Sat\n07-Mar', 'Sun\n08-Mar'], ['Ratna\nSalim', '', '1445-1845\nAGT1', '', '', '1445-1845\nAGT1', '', ''], ['Alex\nYe', '', '', '', '', '', '', ''], ['Ann\nKim', '', '1445-1845\nAGT1', '1445-1845\nAGT1', '', '1415-1815\nTKT', '', '1545-1945\nAGT1'], ['Saeko\nSumi', '', '1215-1915 FC', '1215-1915 FC', '1215-1915 FC', '1215-1915 FC', '1215-1915 FC', ''], ['Joey\nLu', '1115-1915\nSUP', '1115-1915\nSUP', '', '1115-1915\nSUP', '', '1115-1915\nSUP', '1215-2015\nOPS'], ['Cindy\nXiao', '', '', '1145-1845\nARR+DEP', '', '1445-1845\nAGT1', '', '1245-1945\nARR+DEP'], ['Satomi\nHarward', '1145-1845\nARR+DEP', '1145-1845\nARR+DEP', '', '', '1145-1845\nARR+DEP', '1145-1845\nARR+DEP', '1245-1945\nARR+DEP'], ['Kohei\nTodoroki', '', '1415-1815\nTKT', '', '1415-1815\nTKT', '', '', '1515-1915\nTKT'], ['Rich\nHung', '', '', '', '1445-1845\nAGT1', '', '1445-1845\nAGT1', ''], ['Cecillia\nZhu', '', '1145-1845 WT', '1145-1845 WT', '', '1145-1845 WT', '1145-1845 WT', '1245-1945 WT'], ['Donia\nForbes', '1445-1845\nAGT1', '', '1445-1845\nAGT1', '1445-1845\nAGT1', '', '', ''], ['Kevin\nLee', '1145-1845\nARR+DEP', '1145-1845\nARR+DEP', '', '', '', '', ''], ['Crystal\nDeng', '1215-1915 FC', '', '', '1145-1845\nARR+DEP', '1145-1845\nARR+DEP', '1145-1845\nARR+DEP', '1315-2015 FC'], ['Eunsol\nChoi', '1445-1845\nAGT1', '1445-1845\nAGT1', '', '1445-1845\nAGT1', '1445-1845\nAGT1', '', ''], ['Angel\nYeh', '1415-1815\nTKT', '', '1145-1815\nARR+TKT', '1145-1845\nARR+DEP', '', '1415-1815\nTKT', '1545-1945\nAGT1'], ['Willow\nPark', '', '1445-1845\nAGT1', '', '1445-1845\nAGT1', '', '', ''], ['Yumi\nKwon', '1445-1845\nAGT1', '1115-1915\nOPS', '1445-1845\nAGT1', '1115-1915\nOPS', '', '1115-1915\nOPS', ''], ['JoJo\nWang', '', '', '', '', '1445-1845\nAGT1', '1445-1845\nAGT1', '1545-1945\nAGT1'], ['RJ\nArellano', '1145-1845 WT', '1445-1845\nAGT1', '1445-1845\nAGT1', '1145-1845 WT', '1445-1845\nAGT1', '', ''], ['Cody\nLeung', '1115-1915\nOPS', '', '1115-1915\nOPS', '', '1115-1915\nOPS', '', ''], ['Ian\nMaccarthy', '1445-1845\nAGT1', '', '1445-1845\nAGT1', '1445-1845\nAGT1', '', '1445-1845\nAGT1', '1545-1945\nAGT1'], ['Harleen\nHothi', '1445-1845\nAGT1', '', '1445-1845\nAGT1', '', '', '1445-1845\nAGT1', ''], ['Chloe\nWang', '', '', '', '', '', '1445-1845\nAGT1', '1545-1945\nAGT1'], ['', None, None, None, None, None, None, None]]

In [7]:
pd.DataFrame(table)

,0,1,2,3,4,5,6,7
0,MAR 2026,Mon\n02-Mar,Tue\n03-Mar,Wed\n04-Mar,Thu\n05-Mar,Fri\n06-Mar,Sat\n07-Mar,Sun\n08-Mar
1,Ratna\nSalim,,1445-1845\nAGT1,,,1445-1845\nAGT1,,
2,Alex\nYe,,,,,,,
3,Ann\nKim,,1445-1845\nAGT1,1445-1845\nAGT1,,1415-1815\nTKT,,1545-1945\nAGT1
4,Saeko\nSumi,,1215-1915 FC,1215-1915 FC,1215-1915 FC,1215-1915 FC,1215-1915 FC,
5,Joey\nLu,1115-1915\nSUP,1115-1915\nSUP,,1115-1915\nSUP,,1115-1915\nSUP,1215-2015\nOPS
6,Cindy\nXiao,,,1145-1845\nARR+DEP,,1445-1845\nAGT1,,1245-1945\nARR+DEP
7,Satomi\nHarward,1145-1845\nARR+DEP,1145-1845\nARR+DEP,,,1145-1845\nARR+DEP,1145-1845\nARR+DEP,1245-1945\nARR+DEP
8,Kohei\nTodoroki,,1415-1815\nTKT,,1415-1815\nTKT,,,1515-1915\nTKT
9,Rich\nHung,,,,1445-1845\nAGT1,,1445-1845\nAGT1,
10,Cecillia\nZhu,,1145-1845 WT,1145-1845 WT,,1145-1845 WT,1145-1845 WT,1245-1945 WT
11,Donia\nForbes,1445-1845\nAGT1,,1445-1845\nAGT1,1445-1845\nAGT1,,,
12,Kevin\nLee,1145-1845\nARR+DEP,1145-1845\nARR+DEP,,,,,
13,Crystal\nDeng,1215-1915 FC,,,1145-1845\nARR+DEP,1145-1845\nARR+DEP,1145-1845\nARR+DEP,1315-2015 FC
14,Eunsol\nChoi,1445-1845\nAGT1,1445-1845\nAGT1,,1445-1845\nAGT1,1445-1845\nAGT1,,
15,Angel\nYeh,1415-1815\nTKT,,1145-1815\nARR+TKT,1145-1845\nARR+DEP,,1415-1815\nTKT,1545-1945\nAGT1
16,Willow\nPark,,1445-1845\nAGT1,,1445-1845\nAGT1,,,
17,Yumi\nKwon,1445-1845\nAGT1,1115-1915\nOPS,1445-1845\nAGT1,1115-1915\nOPS,,1115-1915\nOPS,
18,JoJo\nWang,,,,,1445-1845\nAGT1,1445-1845\nAGT1,1545-1945\nAGT1
19,RJ\nArellano,1145-1845 WT,1445-1845\nAGT1,1445-1845\nAGT1,1145-1845 WT,1445-1845\nAGT1,,
20,Cody\nLeung,1115-1915\nOPS,,1115-1915\nOPS,,1115-1915\nOPS,,
21,Ian\nMaccarthy,1445-1845\nAGT1,,1445-1845\nAGT1,1445-1845\nAGT1,,1445-1845\nAGT1,1545-1945\nAGT1
22,Harleen\nHothi,1445-1845\nAGT1,,1445-1845\nAGT1,,,1445-1845\nAGT1,
23,Chloe\nWang,,,,,,1445-1845\nAGT1,1545-1945\nAGT1
24,,None,None,None,None,None,None,None

In [8]:
with pdfplumber.open("Monthly Schedule _ MAR.pdf") as pdf:
    page = pdf.pages[0]
    text = page.extract_text()

print(text)

Mon Tue Wed Thu Fri Sat Sun
MAR 2026
02-Mar 03-Mar 04-Mar 05-Mar 06-Mar 07-Mar 08-Mar
Ratna 1445-1845 1445-1845
Salim AGT1 AGT1
Alex
Ye
Ann 1445-1845 1445-1845 1415-1815 1545-1945
Kim AGT1 AGT1 TKT AGT1
Saeko
1215-1915 FC 1215-1915 FC 1215-1915 FC 1215-1915 FC 1215-1915 FC
Sumi
Joey 1115-1915 1115-1915 1115-1915 1115-1915 1215-2015
Lu SUP SUP SUP SUP OPS
Cindy 1145-1845 1445-1845 1245-1945
Xiao ARR+DEP AGT1 ARR+DEP
Satomi 1145-1845 1145-1845 1145-1845 1145-1845 1245-1945
Harward ARR+DEP ARR+DEP ARR+DEP ARR+DEP ARR+DEP
Kohei 1415-1815 1415-1815 1515-1915
Todoroki TKT TKT TKT
Rich 1445-1845 1445-1845
Hung AGT1 AGT1
Cecillia
1145-1845 WT 1145-1845 WT 1145-1845 WT 1145-1845 WT 1245-1945 WT
Zhu
Donia 1445-1845 1445-1845 1445-1845
Forbes AGT1 AGT1 AGT1
Kevin 1145-1845 1145-1845
Lee ARR+DEP ARR+DEP
Crystal 1145-1845 1145-1845 1145-1845
1215-1915 FC 1315-2015 FC
Deng ARR+DEP ARR+DEP ARR+DEP
Eunsol 1445-1845 1445-1845 1445-1845 1445-1845
Choi AGT1 AGT1 AGT1 AGT1
Angel 1415-1815 1145-1815 1145-1845 1415-1815 1545-1945
Yeh TKT ARR+TKT ARR+DEP TKT AGT1
Willow 1445-1845 1445-1845
Park AGT1 AGT1
Yumi 1445-1845 1115-1915 1445-1845 1115-1915 1115-1915
Kwon AGT1 OPS AGT1 OPS OPS
JoJo 1445-1845 1445-1845 1545-1945
Wang AGT1 AGT1 AGT1
RJ 1445-1845 1445-1845 1445-1845
1145-1845 WT 1145-1845 WT
Arellano AGT1 AGT1 AGT1
Cody 1115-1915 1115-1915 1115-1915
Leung OPS OPS OPS
Ian 1445-1845 1445-1845 1445-1845 1445-1845 1545-1945
Maccarthy AGT1 AGT1 AGT1 AGT1 AGT1
Harleen 1445-1845 1445-1845 1445-1845
Hothi AGT1 AGT1 AGT1
Chloe 1445-1845 1545-1945
Wang AGT1 AGT1

In [9]:
with pdfplumber.open("Monthly Schedule _ MAR.pdf") as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

for w in words[:20]:
    print(w)

{'text': 'Mon', 'x0': 103.44, 'x1': 123.0912, 'top': 57.593279999999936, 'doctop': 57.593279999999936, 'bottom': 68.63328000000001, 'upright': True, 'height': 11.040000000000077, 'width': 19.651200000000003, 'direction': 'ltr'}
{'text': 'Tue', 'x0': 177.26, 'x1': 193.62127999999998, 'top': 57.593279999999936, 'doctop': 57.593279999999936, 'bottom': 68.63328000000001, 'upright': True, 'height': 11.040000000000077, 'width': 16.361279999999994, 'direction': 'ltr'}
{'text': 'Wed', 'x0': 247.13, 'x1': 267.97216, 'top': 57.593279999999936, 'doctop': 57.593279999999936, 'bottom': 68.63328000000001, 'upright': True, 'height': 11.040000000000077, 'width': 20.84215999999998, 'direction': 'ltr'}
{'text': 'Thu', 'x0': 321.43, 'x1': 337.92375999999996, 'top': 57.593279999999936, 'doctop': 57.593279999999936, 'bottom': 68.63328000000001, 'upright': True, 'height': 11.040000000000077, 'width': 16.493759999999952, 'direction': 'ltr'}
{'text': 'Fri', 'x0': 396.19, 'x1': 407.6164, 'top': 57.593279999999936, 'doctop': 57.593279999999936, 'bottom': 68.63328000000001, 'upright': True, 'height': 11.040000000000077, 'width': 11.426400000000001, 'direction': 'ltr'}
{'text': 'Sat', 'x0': 466.66, 'x1': 481.44256, 'top': 57.593279999999936, 'doctop': 57.593279999999936, 'bottom': 68.63328000000001, 'upright': True, 'height': 11.040000000000077, 'width': 14.78255999999999, 'direction': 'ltr'}
{'text': 'Sun', 'x0': 537.48, 'x1': 554.6803199999999, 'top': 57.593279999999936, 'doctop': 57.593279999999936, 'bottom': 68.63328000000001, 'upright': True, 'height': 11.040000000000077, 'width': 17.20031999999992, 'direction': 'ltr'}
{'text': 'MAR', 'x0': 23.88, 'x1': 46.11456, 'top': 64.31327999999996, 'doctop': 64.31327999999996, 'bottom': 75.35328000000004, 'upright': True, 'height': 11.040000000000077, 'width': 22.23456, 'direction': 'ltr'}
{'text': '2026', 'x0': 48.21216, 'x1': 72.15792, 'top': 64.31327999999996, 'doctop': 64.31327999999996, 'bottom': 75.35328000000004, 'upright': True, 'height': 11.040000000000077, 'width': 23.945760000000007, 'direction': 'ltr'}
{'text': '02-Mar', 'x0': 96.96, 'x1': 129.53904, 'top': 72.11327999999992, 'doctop': 72.11327999999992, 'bottom': 83.15328, 'upright': True, 'height': 11.040000000000077, 'width': 32.579040000000006, 'direction': 'ltr'}
{'text': '03-Mar', 'x0': 169.1, 'x1': 201.67904000000001, 'top': 72.11327999999992, 'doctop': 72.11327999999992, 'bottom': 83.15328, 'upright': True, 'height': 11.040000000000077, 'width': 32.57904000000002, 'direction': 'ltr'}
{'text': '04-Mar', 'x0': 241.25, 'x1': 273.82903999999996, 'top': 72.11327999999992, 'doctop': 72.11327999999992, 'bottom': 83.15328, 'upright': True, 'height': 11.040000000000077, 'width': 32.579039999999964, 'direction': 'ltr'}
{'text': '05-Mar', 'x0': 313.37, 'x1': 345.94903999999997, 'top': 72.11327999999992, 'doctop': 72.11327999999992, 'bottom': 83.15328, 'upright': True, 'height': 11.040000000000077, 'width': 32.579039999999964, 'direction': 'ltr'}
{'text': '06-Mar', 'x0': 385.51, 'x1': 418.08903999999995, 'top': 72.11327999999992, 'doctop': 72.11327999999992, 'bottom': 83.15328, 'upright': True, 'height': 11.040000000000077, 'width': 32.579039999999964, 'direction': 'ltr'}
{'text': '07-Mar', 'x0': 457.66, 'x1': 490.23904, 'top': 72.11327999999992, 'doctop': 72.11327999999992, 'bottom': 83.15328, 'upright': True, 'height': 11.040000000000077, 'width': 32.579039999999964, 'direction': 'ltr'}
{'text': '08-Mar', 'x0': 529.8, 'x1': 562.37904, 'top': 72.11327999999992, 'doctop': 72.11327999999992, 'bottom': 83.15328, 'upright': True, 'height': 11.040000000000077, 'width': 32.57904000000008, 'direction': 'ltr'}
{'text': 'Ratna', 'x0': 20.4, 'x1': 46.664159999999995, 'top': 86.27328, 'doctop': 86.27328, 'bottom': 97.31328000000008, 'upright': True, 'height': 11.040000000000077, 'width': 26.264159999999997, 'direction': 'ltr'}
{'text': '1445-1845', 'x0': 160.22, 'x1': 210.15312, 'top': 85.19327999999996, 'doctop': 85.19327999999996, 'bottom': 96.23328000000004, 'upright': True, 'height': 11.040000000000077, 'width': 49.93312, 'direction': 'ltr'}
{'text': '1445-1845', 'x0': 376.63, 'x1': 426.56311999999997, 'top': 85.19327999999996, 'doctop': 85.19327999999996, 'bottom': 96.23328000000004, 'upright': True, 'height': 11.040000000000077, 'width': 49.933119999999974, 'direction': 'ltr'}
{'text': 'Salim', 'x0': 49.68, 'x1': 74.84016, 'top': 100.19327999999996, 'doctop': 100.19327999999996, 'bottom': 111.23328000000004, 'upright': True, 'height': 11.040000000000077, 'width': 25.160159999999998, 'direction': 'ltr'}