# Compass Dashboard

In [2]:
import pandas as pd
import pdfplumber
import sys
import os
sys.path.append(os.path.abspath(".."))

## Intro

Like many mid-sized companies, my groundhandling agency at Vancouver airport loves to distribute employee rosters in the form of pdf documents. Our schedules are laid out in unloveable tables that are neither machine readable nor copy-paste-able. This format is inconvenient to read for one employee, as each schedule table represents just one week rather than a whole month. To manually copy out my shifts for later reference involves a lot of scrolling and double-checking. The first part of my project is to build a data pipeline that will parse my schedule PDF document and return a clean list of my shifts for the month.


The second part of my project is to build a decision-making tool that will help me to decide how to pay for transit over the coming month. The fare rules for travelling to and from the airport are complicated, with different fares charged depending on the time of day, day of the week, and point of origin. Translink passengers can pay any of these fares conveniently with a compass card, which can be loaded with cash (stored value) or with a monthly pass covering any number of Vancouver's transit zones. Calculating by hand exactly how much it will cost to commute to the airport for all of my shifts under different payment scenarios is a tedious and repetitive process, and I want to create a dashboard that will instantly show me all the figures I need to pick the most cost-effective option, as well as compare the benifits offered by alternative options.

## Data Extraction

To first extract shift information from these roster tables, I used the `pdfplumber` library, which contains a range of functions for dealing with pdf documents. `pdfplumber` actually includes a handy `extract_table()` function that will under most circumstances convert PDF tables into dataframes. I try it out here to see how it goes:

In [3]:
with pdfplumber.open("../data/Monthly Schedule _ MAY.pdf") as pdf:
    page = pdf.pages[0]
    table = page.extract_table()
pd.DataFrame(table).head()

,0,1,2,3,4,5,6,7
0,MAY 2026,Mon\n04-May,Tue\n05-May,Wed\n06-May,Thu\n07-May,Fri\n08-May,Sat\n09-May,Sun\n10-May
1,Ratna\nSalim,,,1715-2115 GT1,,1715-2115 GT1,,
2,Alex\nYe,1715-2115 GT1,,,1330-2100\nARR+DEP,1715-2115 GT1,1715-2115 GT1,1715-2115 GT1
3,Ann\nKim,,1630-2030 TKT,1630-2030 TKT,1630-2030 TKT,1630-2030 TKT,,1630-2030 TKT
4,Saeko\nSumi,1415-2115 FC,1415-2115 FC,1415-2115 FC,,1415-2115 FC,1415-2115 FC,

So in fact with this specific document it would be easy to take this shortcut and proceed from here. However, I was curious to learn more about PDF parsing and so I chose to start with the same library's `extract_words()` function, wich extract words along with their geometric positions, and write my own parsing function to reconstruct the table data. My function `parse_pdf()` below is a wrapper for `extract_words()` along with several other custom extractor functions that search the flattened text for a given employee's name and retrieves all of their shift times and shift types.

In [ ]:

from src.parser.orchestrator import parse_pdf
data = parse_pdf('../data/Monthly Schedule _ MAY.pdf')
data[:5]

[{'date': '05-May', 'time': '1715-2115', 'type': 'GT1'},
 {'date': '06-May', 'time': '1715-2115', 'type': 'GT1'},
 {'date': '07-May', 'time': '1715-2115', 'type': 'GT1'},
 {'date': '12-May', 'time': '1715-2115', 'type': 'GT1'},
 {'date': '13-May', 'time': '1715-2115', 'type': 'GT1'}]

In [7]:
df = pd.DataFrame(data)
df.head()

     date       time type
0  05-May  1715-2115  GT1
1  06-May  1715-2115  GT1
2  07-May  1715-2115  GT1
3  12-May  1715-2115  GT1
4  13-May  1715-2115  GT1

This is all the information that I need parsed correctly from the original document, but its current format leaves a bit to be desired. The `clean_dataframe()` function below splits the time column into separate start and end times, as well as standardizing the spacing and capitalisation of all values and column names as a way to future-proof the code. It also performs a quick validation of the data and will raise an error if there are any missing dates or time values.

In [8]:
from src.processing.cleaning import clean_dataframe

df = clean_dataframe(df)
df.head()

     date       time type start_time end_time
0  05-May  1715-2115  GT1       1715     2115
1  06-May  1715-2115  GT1       1715     2115
2  07-May  1715-2115  GT1       1715     2115
3  12-May  1715-2115  GT1       1715     2115
4  13-May  1715-2115  GT1       1715     2115

Now the data is in a much more useable form, but the dates are still just strings. An obvious improvement would be to transform them into datetime objects, which is what the `add_datetime_columns()`  and `parse_times()` functions do. Note that it takes a start year for the schedule, as this can't be inferred directly from the PDF document, and will automatically increment the year in case the date range spans January 1st.

In [ ]:
from src.processing.datetime_utils import add_datetime_columns, parse_times

df = add_datetime_columns(df, start_year=2026)
df = parse_times(df)
df.head()

        date       time type          start_time            end_time
0 2026-05-05  1715-2115  GT1 2026-05-05 17:15:00 2026-05-05 21:15:00
1 2026-05-06  1715-2115  GT1 2026-05-06 17:15:00 2026-05-06 21:15:00
2 2026-05-07  1715-2115  GT1 2026-05-07 17:15:00 2026-05-07 21:15:00
3 2026-05-12  1715-2115  GT1 2026-05-12 17:15:00 2026-05-12 21:15:00
4 2026-05-13  1715-2115  GT1 2026-05-13 17:15:00 2026-05-13 21:15:00

And from there I can add a few extra features that will be useful when calculating transit costs, using only the datetimes in the first column.

In [ ]:
from src.processing.features import add_features

df = add_features(df)

df.head()

Wrapping this all together into a pipeline I can create this dataframe with a single function call.

In [ ]:
from src.pipeline import run_pipeline

df = run_pipeline('../data/Monthly Schedule _ MAY.pdf', start_year=2026)

df.head()

In [ ]:
from src.logic.trips import ShiftsToTrips

In [ ]:
trips = ShiftsToTrips(df, 90)
trips.head()

In [ ]:
trips.shape

In [ ]:
from src.logic.trips import GetOneZoneTrips, count_trip_types

In [ ]:
GetOneZoneTrips(trips).head()

In [ ]:
counts = count_trip_types(trips)
pd.DataFrame.from_dict(counts, orient='index', columns=['Trips'])

In [ ]:
from src.config.fare_prices import FARES

In [ ]:
FARES.one_zone

In [ ]:
from src.logic.fares import cost_one_zone_pass

In [ ]:
cost_one_zone_pass(counts,FARES)

In [ ]:
from src.logic.costs import total_costs

In [ ]:
total_costs(df, FARES, 60)['costs']